version: '2'

services:
  sphinx:
    build:
        context: .
        dockerfile: Dockerfile.sphinx
    container_name: graph-docs
    working_dir: /code
    command: bash -c 'make html && make latex && cd build/latex && make'
    volumes:
      - ./:/code
  runner:
    build: .
    container_name: graph-runner
    working_dir: /code
    command: bash -c ''
    volumes:
      - ./:/code
  test:
    build: .
    container_name: graph-test
    working_dir: /code
    command: bash -c 'python setup.py test'
    volumes:
      - ./:/code
