version: '2'

services:
  runner:
    build: .
    container_name: graph-runner
    working_dir: /code
    command: bash -c ''
    volumes:
      - ./:/code
  test:
    build: .
    container_name: graph-test
    working_dir: /code
    command: bash -c 'python setup.py test'
    volumes:
      - ./:/code
